name: Code Quality

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint with detailed output
        run: npm run lint -- --format=stylish

      - name: Check Prettier formatting
        run: npm run format -- --check --write=false

      - name: Security audit
        run: npm audit --audit-level=moderate

      - name: Check for outdated dependencies
        run: npm outdated || true

      - name: Validate package.json
        run: |
          node -e "
            const pkg = require('./package.json');
            if (!pkg.name || !pkg.version || !pkg.description) {
              throw new Error('package.json missing required fields');
            }
            console.log('✓ package.json is valid');
          "

      - name: Validate documentation
        run: |
          # Check that user guide exists and has content
          if [ ! -f docs/user-guide.md ] || [ ! -s docs/user-guide.md ]; then
            echo "❌ User guide is missing or empty"
            exit 1
          fi

          # Check that README has reasonable content
          if [ $(wc -l < README.md) -lt 10 ]; then
            echo "❌ README.md appears to be too short"
            exit 1
          fi

          echo "✓ Documentation validation passed"
